Feature/select issues
suhlimakz/issue-tracker pull request #7
Opened 2021-03-03 09:04 UTC by suhlimakz

2021-03-03 19:46 UTC, RobsonAndraDev requested changes

2021-03-03 19:46 UTC, RobsonAndraDev commented on back-end/src/services/issue.js
> +  selectIssuesActive = JSON.parse( selectIssuesActive );
Não faz muito sentido transformar o json em string pra logo depois trasformar ele em json novamente.
remover esses JSON.algumaCoisa

2021-03-03 19:46 UTC, RobsonAndraDev commented on back-end/src/services/issue.js
> +  return { selectIssuesActive } ;
A msg não era pra ir junto com esse return?

2021-03-15 17:24 UTC, suhlimakz commented on back-end/src/services/issue.js
> +  return { selectIssuesActive } ;
Me esqueci de colocar :sweat_smile:

2021-03-15 19:08 UTC, RobsonAndraDev approved these changes

2021-03-15 20:00 UTC, merged