Feature/update user
suhlimakz/issue-tracker pull request #8
Opened 2021-03-15 19:42 UTC by suhlimakz

2021-03-15 20:17 UTC, RobsonAndraDev requested changes

2021-03-15 20:17 UTC, RobsonAndraDev commented on back-end/src/models/issue.js
> +  const [ results ] = await connection.query( sql );
vc não precisa criar essa constante já que não usara em momento algum

2021-03-15 20:17 UTC, RobsonAndraDev commented on back-end/src/models/users.js
> +  const [ reults ] = await connection.query( sql );
Mesmo comentário anterior, com o agravante do nome dela estar errado aqui

2021-03-22 19:33 UTC, suhlimakz commented on back-end/src/models/issue.js
> +  const [ results ] = await connection.query( sql );
Corrigido na branch main.

2021-03-22 19:33 UTC, suhlimakz commented on back-end/src/models/users.js
> +  const [ reults ] = await connection.query( sql );
Corrigido

2021-03-23 16:15 UTC, RobsonAndraDev approved these changes

2021-03-30 16:57 UTC, merged